version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3326:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=password
      - TZ=America/Sao_Paulo
    volumes:
      - ./mysql/data:/var/lib/mysql
